### ISSUE TITLE
Unable to create channel, category, roles or host on my ip network.

### ISSUE THREAD

**Issue by fartabomination** [xinweny/discord-clone#2]
Whenever I try to add a channel, role or category, I get an issue similar to this 

```bat
[0] CustomError: Unauthorized
[0]     at authorizeMiddleware (file:///D:/discord-clone/backend/src/middleware/authorize.ts:1:1007)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]     at async file:///D:/discord-clone/backend/src/helpers/tryCatch.ts:1:199 {
[0]   statusCode: 403,
[0]   error: null
[0] }
```

Any reason as to why?

**Comment by xinweny** [comment]
Hi, thanks for pointing out the issue. The bug should be resolved now.

The error had to do with the `.equals()` method not being found on the ObjectId's `.prototype` attribute within the mongoose schema instance method that checks server role permissions. It seems `.equals()` is still present on the ObjectId itself (despite Typescript complaining otherwise), so accessing it directly on the ObjectId seems to have fixed it.

**Comment by fartabomination** [comment]
> Hi, thanks for pointing out the issue. The bug should be resolved now.
> 
> The error had to do with the `.equals()` method not being found on the ObjectId's `.prototype` attribute within the mongoose schema instance method that checks . It seems `.equals()` is still present on the ObjectId itself (despite Typescript complaining otherwise), so accessing it directly on the ObjectId seems to have fixed it.

Thanks heaps!

**Comment by fartabomination** [comment]
Unfortunately I am still unable to create roles..

**Comment by xinweny** [comment]
Hi again, so sorry about this - there was a bug where the role permission default values weren't present, so I fixed it. You should now be able to create roles.

I created this app as a portfolio project and more importantly to learn how to use Express, MongoDB and lots of other techs, so there are probably still bugs here and there, especially since I did upgrade the package versions sometime back as well.

I'm still learning but I will do my best, so I really do appreciate your patience and for pointing out these issues - they do help me learn a lot.

When I have more time, I am planning to revisit this application and iron out the kinks more, and add proper test files.

**Comment by fartabomination** [comment]
> Hi again, so sorry about this - there was a bug where the role permission default values weren't present, so I fixed it. You should now be able to create roles.
> 
> I created this app as a portfolio project and more importantly to learn how to use Express, MongoDB and lots of other techs, so there are probably still bugs here and there, especially since I did upgrade the package versions sometime back as well.
> 
> I'm still learning but I will do my best, so I really do appreciate your patience and for pointing out these issues - they do help me learn a lot.
> 
> When I have more time, I am planning to revisit this application and iron out the kinks more, and add proper test files.

Don't be sorry! This fix kinda worked for me. However now this page is out of proportion. 
![image](https://github.com/xinweny/discord-clone/assets/115855298/c50d1bca-d146-4df7-b41d-11256f46ce7c)

And another thing (if its not too hard to ask), is it possible to add badges and a staff badge to certain users (defined in mongodb or a json or something)?

**Comment by fartabomination** [comment]
Also there does not seem to be an option to display roles seperatly to online users.

**Comment by xinweny** [comment]
Yup those layout/styling fixes should be pretty quick to do - however, could you clarify what you mean by badges and staff badges? Right now, only the server owner badge will be shown in the server panel next to the server owner's name, in the list of server members.

By displaying roles separately to online users, does that mean to split online users by their roles in the server member list? That was one of the features I was planning to implement eventually - I think I would need to implement a role priority "score" to determine which is the most important role a user has (which would be the one to display) in order to do that effectively.

That's the idea I had at least, and I'd need to put some time aside to implement this feature. If you have any suggestions though I would be more than happy to hear it!

I can get the fixes done and take a full look at your suggestions in the morning if that's alright, since it's getting late here.

**Comment by fartabomination** [comment]
> Yup those layout/styling fixes should be pretty quick to do - however, could you clarify what you mean by badges and staff badges? Right now, only the server owner badge will be shown in the server panel next to the server owner's name, in the list of server members.
> 
> By displaying roles separately to online users, does that mean to split online users by their roles in the server member list? That was one of the features I was planning to implement eventually - I think I would need to implement a role priority "score" to determine which is the most important role a user has (which would be the one to display) in order to do that effectively.
> 
> That's the idea I had at least, and I'd need to put some time aside to implement this feature. If you have any suggestions though I would be more than happy to hear it!
> 
> I can get the fixes done and take a full look at your suggestions in the morning if that's alright, since it's getting late here.

My apologies but as in staff badge I was referring to this 
![image](https://github.com/xinweny/discord-clone/assets/115855298/5f08fb7e-1bed-4380-a2b5-3b028d54cd73)

**Comment by fartabomination** [comment]
Also here is the exact icon that the badge would have, 
![image](https://github.com/xinweny/discord-clone/assets/115855298/6bc57ad2-3d5b-41fb-9f54-12fceac82434)

**Comment by fartabomination** [comment]
Also I apologise to bother you again but when I use
```bat
npm run dev -- --host 192.168.1.124
```

I am able to run the page on other devices at
```bat
http://192.168.1.124:5173/
```

However I cannot sign in or register on any device unless I use
```bat
localhost:5173
```

on the device that is running on the server. I tried logging in on my pc and then my phone but only the pc on localhost worked.

**Comment by fartabomination** [comment]
Alright so after further inspection I found it to be related to "CORS". I installed https://chromewebstore.google.com/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino?pli=1 for testing and it worked. Are you able to fix this issue?

**Comment by fartabomination** [comment]
Also I noticed this small thing. 
![image](https://github.com/xinweny/discord-clone/assets/115855298/d45ab219-62b0-4d04-bcdd-184b654f5764)

**Comment by fartabomination** [comment]
So sorry, one other thing is that you cannot DM another user.

**Comment by xinweny** [comment]
So far I have fixed the following issues:

1. DMing users is now working
2. Long message character wraps onto newline correctly
3. As for the CORS issue, I think you would have to set the `CLIENT_URL` parameter in `.env` as `http://192.168.1.124:5173`

After some consideration, I don't think I will be introducing any new staff badge features for now, as my intention with this application was to demonstrate my ability to recreate some of Discord's core features, so I'd like to refine those as much as I can.

Moving forward, I'd appreciate if you could please create separate issues for each individual bug you encounter, so I may track them more easily. Thanks :)
